spring:
  datasource:
    
    url: 
      jdbc:mariadb://192.168.1.100/db_springboot_backend?useSSL=false
    username: 
      root
    password: 
      3ntr4r
    driver-class-name: 
      org.mariadb.jdbc.Driver
  jpa:
    database-platform: 
      org.hibernate.dialect.MariaDB103Dialect
    hibernate.ddl-auto: 
      create-drop
      
logging:
  level:
    org:
      hibernate:
        SQL: debug
    